### ISSUE TITLE
Todo's

### ISSUE THREAD

**Issue by saranonearth** [photog-nitkkr/confluence-frontend-2019#27]
Following are the tasks to be done 
- [x] Home - Ayush/Ekta
- [x] Team Confluence - Ayush/Ekta
- [x] Developers - Ayush/Ekta
- [x] Sponsor - Ayush/Ekta
- [x] Events - Saran
- [x] Categories - Saran
- [x] Event description - Saran
- [x] Auth/Event Registration - Saran
- [x] HomePage Scroll
Optional 
- [x] Use react transition group package to throw some transition between component render

**Comment by saranonearth** [comment]
Events| Categories| Event Description
